### PR TITLE
MNT: rerender

### LINKED ISSUE #39: @conda-forge-admin rerender
- [ ] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

```
</details>

### PR DESCRIPTION
**Pull request by conda-forge-linter**
Hi! This is the friendly automated conda-forge-webservice.

I've rerendered the recipe as instructed in #39.

Here's a checklist to do before merging.
- [ ] Bump the build number if needed.

Fixes #39

### CODE REVIEW

**Comment by beckermr** [comment]
@conda-forge-admin rerender

**Comment by beckermr** [comment]
@conda-forge/mpb this pr fixes this build so it pins mpich correctly. Please merge if you are ok with it!

**Comment by oskooi** [comment]
Thanks for putting this together @beckermr. Is it necessary to also pin mpich in https://github.com/conda-forge/pymeep-feedstock/blob/master/recipe/conda_build_config.yaml?

**Comment by beckermr** [comment]
No. We no longer use pin_run_as_build. Instead we rely on run exports in the mpich and openmpi packages.

**Comment by beckermr** [comment]
The global pins from the conda-forge global pinning files will be used.

**Comment by beckermr** [comment]
See our documentation for the current correct way to build with mpi: https://conda-forge.org/docs/maintainer/knowledge_base.html#building-mpi-variants

This has changed semi-recently and we are cleaning up repos with the old way as we find them.

**Pull request merged**
