### PR TITLE
Add ppc64le support.

### LINKED ISSUE #23: Add ppc64le support?
I would like to have support for ppc64le for this package. I will try to make a PR.

### PR DESCRIPTION
**Pull request by bdice**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Closes #23 by adding support for ppc64le (the IBM POWER architecture) and aarch64 (ARM64).

### CODE REVIEW

**Comment by bdice** [comment]
@conda-forge-admin, please rerender

**Comment by bdice** [comment]
@conda-forge-admin, please rerender

**Comment by oskooi** [comment]
@conda-forge-admin, please rerender

**Comment by bdice** [comment]
@oskooi @ChristopherHogan I think this is ready to review. Thanks again!

**Comment by oskooi** [comment]
This looks fine. Would you also create a similar PR for the Meep Conda package: https://github.com/conda-forge/pymeep-feedstock?

**Pull request merged**
